### ISSUE TITLE
Add a unique_id property

### ISSUE THREAD

**Issue by balloob** [GuySie/ha-meural#21]
Entities that have a unique ID allow the user to change the name and entity ID without restarting Home Assistant. It also makes sure that your entity ID is reserved for this entity.

Unique ID should be a unique identifier like a serial number or mac address.

**Comment by GuySie** [comment]
@balloob Ooh, nice. I was wondering how to get that. Added in commit https://github.com/GuySie/ha-meural/commit/df3a2ae483ba08bbff863c94c7cba82f9f7da87d using the productKey (serial number) as identifier.

Does this require anything beyond adding the property?

**Comment by balloob** [comment]
That's it. Now you can also add device info if you haven't already. You can use (DOMAIN, productKey) as identifier.

**Comment by GuySie** [comment]
Cool, didn't know we could do that either! Added in commit https://github.com/GuySie/ha-meural/commit/f5e271ca1917302a297c1240a6e64acb07d4567c!
