### ISSUE TITLE
Meural icon does not display yet

### ISSUE THREAD

**Issue by GuySie** [GuySie/ha-meural#22]
When looking for Meural in the integrations list a placeholder icon is shown. Icon refers to:
https://brands.home-assistant.io/_/meural/icon.png
which does not exist yet, but:
https://brands.home-assistant.io/meural/icon.png
does.

Cache issue?

**Comment by ludeeus** [comment]
Yes, that is due to CloudFlare cache, it's set to a week.

**Comment by GuySie** [comment]
@ludeeus Ahhhh then this will resolve itself. Thanks! :)
