### ISSUE TITLE
Meural Photo Frame support

### ISSUE THREAD

**Issue by GuySie** [GuySie/ha-meural#40]
Meural has introduced a new Photo Frame product:
https://meural.netgear.com/photo-frame/

It is currently unknown if HA-meural works with the Photo Frame, as we have no device to test with.

**Comment by Jaharmi** [comment]
Any news/feedback on whether the Photo Frame works with this integration?

**Comment by GuySie** [comment]
Can't confirm nor deny I'm afraid, I don't have a Photo Frame nor have I heard from any owners of Photo Frames whether it has worked for them.

**Comment by snowypineapple** [comment]
Confirming I've been successfully using this with the Photo Frame for the past six months. Also using with a Canvas. Thank you!

Device info for the photo frame:
> Frame II WW
> by NETGEAR
> Firmware: 2.2.12_2.1.7

**Comment by GuySie** [comment]
@snowypineapple That's great news, thanks for the information! I'll close this issue then.
