### ISSUE TITLE
Meural Unavailable after firmware update - Firmware: 2.2.7_2.0.13

### ISSUE THREAD

**Issue by pratikmistry** [GuySie/ha-meural#43]
I just updated the firmware on my Canvas II and the Mini Media card for my Canvas II is now showing unavailable.

**Comment by GuySie** [comment]
Hey @pratikmistry sorry to hear that! My Meural is not on that firmware yet, I will investigate. Have you tried removing and re-adding the integration? It may be just a case of the token changing when the firmware updated.

**Comment by pratikmistry** [comment]
Hi Guy, 

Yes I tried to reinstall it as well, still the same issue.  It’s not a big deal but it was nice when it was working lol.  It’s such an underrated add on

**Comment by GuySie** [comment]
@pratikmistry Great to hear you like it, I'd love to try and keep it working for you :) 
Do you know how to get the log out of your Home Assistant? It'd be very helpful for me if you could set your log level to debug, reboot HA, and then wait a few minutes for everything to have started up. Then if you could send me that log file (you can attach it here) I can check if there's any obvious causes for the integration to fail.

**Comment by pratikmistry** [comment]
Would this be it?  Sent from Mail for Windows 10 From: Guy SieSent: May 31, 2021 10:44 AMTo: GuySie/ha-meuralCc: pratikmistry; MentionSubject: Re: [GuySie/ha-meural] Meural Unavailable after firmware update - Firmware: 2.2.7_2.0.13 (#43) Great to hear you like it, I'd love to try and keep it working for you :)Do you know how to get the log out of your Home Assistant? It'd be very helpful for me if you could set your log level to debug, reboot HA, and then wait a few minutes for everything to have started up. Then if you could send me that log file (you can attach it here) I can check if there's any obvious causes for the integration to fail.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by GuySie** [comment]
@pratikmistry No, but let me give you a quick link to help you find it!

Your log file is called `home-assistant.log` and is stored in the same folder as your Home Assistant `configuration.yaml` file. It's overwritten each time you restart HA:
https://www.home-assistant.io/integrations/logger/

If you restart your HA, then wait a few minutes after everything has started up, then could find this log file and attach it here - that would already be very helpful!

**Comment by GuySie** [comment]
@pratikmistry I've updated my Meural Canvas to the newest firmware for a while now so I can test with the integration, but have not been able to reproduce this problem. I'm going to close the issue, but feel free to reopen it if you can provide me with a log!
