### ISSUE TITLE
Integration stopped working, no re-setup possible

### ISSUE THREAD

**Issue by TheDK** [GuySie/ha-meural#47]
Sometime today the Meural stopped working, lots of these:
```
2022-02-05 19:48:18 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.meural_eg fails
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://api.meural.com/v0/devices/***')
```
I thought OK - typical re-auth situation (as this usually is 401 error)...

When I deleted the integration and tried to run setup again, it fails with this error
```
[%key:common::config_flow::abort::cannot_connect%]
```
Login in Meural Web and App are working fine, Meural can be controlled this way.

Anything going on?

**Comment by TheDK** [comment]
Don't know why - it just started working again...

**Comment by GuySie** [comment]
I haven't seen this happen before, but I also got some emails about weird 403 errors happening that I have never experienced before, so there might be something weird going on with the API in general. Will keep an eye out!

**Comment by TheDK** [comment]
Top, thanks!
