### ISSUE TITLE
The media controls don't honor inverted gesture direction setting 

### ISSUE THREAD

**Issue by lkroeker** [GuySie/ha-meural#52]
I'd like to start by saying that this integration overall is awesome; the control of the Meural works really well, quickly and easily, Bravo!

However, one bug is that I have our canvas set to reverse the gesture direction (it feels more natural for swiping images back and forth) and the media 'forward' and 'back' controls are swapped within HA. Hopefully a simple fix of reading that setting from Netgear/Meural, or adding an toggle option in the add-on settings to reverse the control directions. 

Obviously there's an easy workaround for now, so definitely not a high priority issue. 

Screenshot if it's helpful:
![20220718_073105](https://user-images.githubusercontent.com/10866030/179503878-a9e8ebe3-70ad-4e38-8e0c-ea0fa0977a76.jpg)

Thanks!

**Comment by GuySie** [comment]
@lkroeker Thanks for your kind words! I had no idea the gesture direction setting also changed the direction for the hotkeys. Should be a trivial fix, we already get the data for that setting (gestureFlip) by default from the server.

**Comment by GuySie** [comment]
Bugfix in https://github.com/GuySie/ha-meural/commit/cb0515bf4f0ded6ccd2ddaa5dfbd3148dca93dc0 should do it!

**Comment by GuySie** [comment]
And released in https://github.com/GuySie/ha-meural/releases/tag/v1.0.1 :)
