### ISSUE TITLE
2nd Meural "Unavailable"

### ISSUE THREAD

**Issue by cmaglio** [GuySie/ha-meural#53]
Hello, great work on this integration! 

I have 2 Meurals, both seemed to be added without issue during the setup process. However, one of the Meurals seems to work perfectly in HA while the other was instantly "Unavailable" and HA does not appear to be getting any information from it. Both Meurals are "Online" in the Meural Netgear App and I have tried power cycling the "Unavailable" Meural to no avail.

Do you have any suggestions on what I can try to get the 2nd Meural working like the other one?

Working Meural
![image](https://user-images.githubusercontent.com/37604281/202183904-9595d8c2-b5ef-45f9-a2fb-959927412ada.png)

"Unavailable" Meural
![image](https://user-images.githubusercontent.com/37604281/202184149-b82c1275-7496-4d30-a26f-29f3eb512f70.png)

![image](https://user-images.githubusercontent.com/37604281/202185851-818553a7-539e-4ee1-b418-766fb38ebecb.png)

**Comment by cmaglio** [comment]
Update... this morning, the scenario flip flopped and the "Unavailable" Meural started working. At the same exact time, the previously working Meural became "Unavailable". I believe this is too much of a coincidence to happen at the exact same moment. 

Both are still showing "Online" in the Meural App... so, I don't expect this is a device specific or network issue.

![image](https://user-images.githubusercontent.com/37604281/202231626-1011436b-addd-432d-8ed1-b4d483dc123c.png)

![image](https://user-images.githubusercontent.com/37604281/202234060-5c53c609-2957-4b14-a066-121dcb9c4a15.png)

Would there be any reason the integration would only be able to communicate and have one Meural active at any given time?

The status swapped during a reboot of the HA server, so maybe whichever Meural the integration is able to contact first is the one that shows "Available"?

**Comment by GuySie** [comment]
@cmaglio Hmmm, that's an interesting bug! Could you send me a debug log from after a restart, until after the meural devices have finished setting up (so once you can control the one that works)? I have an idea of what might be happening but need a log to see what it says.

**Comment by cmaglio** [comment]
@GuySie  I sent a debug level log to your email. Please let me know if you need more detail than provided. Thank you!

**Comment by GuySie** [comment]
@cmaglio Super, thanks! According to the logs I was thinking in the right direction - but it's kinda weird how the bug is triggering.

Basically, during setup the integration tests if each Meural is reachable on its local IP (as known by the Meural server), and if not it will abort setup for that device. The idea behind it is that if you have multiple Meurals but they're not all on the local network for your HA install, eg you have one at home but also one in the office on the same Meural account, to stop setup for those that are not here. That's why one of your Meurals is unavailable, it can't be reached during setup so it aborts. What I don't understand is why HA couldn't reach it, nor why the unavailable Meural flipped after another restart.

Could you try restarting HA again after making sure that the Meurals are both turned on and that you can successfully control them from the Meural mobile app by going backward and forward through some art on both?

**Comment by cmaglio** [comment]
Interesting... I was able to control both Meurals via the Meural app and then immediately restarted HA. This time... HA wasn't able to establish a connection to either Meural. Yet, when I opened the app, both are still "online" and controllable from the Meural app. 

I have the same errors in the startup logs for both Meurals as the one I sent you.

This has got me scratching my head now as well... I was able to ping both local IPs for both Meurals from my PC. I was also able to ping the below IP addresses from the HA server.

![image](https://user-images.githubusercontent.com/37604281/202307223-859d76a8-da88-4f3a-8ef9-e4abecf1260e.png)

I'm working with a fairly simple and straightforward network topology... I don't have any VLANs or anything that would complicate any two devices from talking directly over the LAN.

Other than being able to ping them, is there anything I should do from the HA server to make sure both are reachable in a way you need them to be?

After a couple more HA restarts, I am back to the original scenario where one is available and the other is not.

**Comment by GuySie** [comment]
@cmaglio Nope, nothing special is needed. The Meural should just respond to a request to the local web remote on your device to get a list of all locally stored playlists. It does only try once, which I suppose may be too aggressive. Let me take a look and see if I can make it a bit more forgiving.

**Comment by GuySie** [comment]
@cmaglio Could you try something for me? After seeing https://github.com/GuySie/ha-meural/issues/54 I think this may be related.

Can you, for both of your Meural devices, check what their local IP is and then go to http://**(fill in the device's local IP here)**/remote in the browser? Do you get a remote control interface for that device, or does it time out? If it times out, is that consistent with the devices you can't control in Home Assistant?

**Comment by cmaglio** [comment]
@GuySie I was able to view the remote URL you mentioned on both Meurals, loaded up in browser almost instantly. I even hit refresh a few times to confirm it was loading consistently and fast. I also confirmed I was able to control both Meurals consistently from those webpages, 

Since that seemed to be working so well... I decided to try to restart HA, and I still only ended up with one Meural being "Active" and the other "Unavailable".

After this, I returned to the "remote" URL webpage and confirmed I was still able to load and control both Meurals from that URL. So, it doesn't appear to be related. 

It looks like #54 was an issue with the Meural being on another private LAN (accidentally) versus I think this issue has to do with running a second instance of the Meural media player. I have been able to reach and control both Meurals consistently by any other method except for the HA integration. The fact that both Meurals can work via the integration at different times, but never together, I believe, is further evidence of this.

**Comment by cmaglio** [comment]
@GuySie Does Meural and this integration, by chance, use UPnP? 

I have been getting some intermittent errors in HA on my Sonos integration as well (UPnP 501 Errors). I was doing some troubleshooting today trying to figure out the source of these Sonos errors... and in the midst of trying to isolate the Sonos errors to a specific device (if possible)... I noticed, for the first time ever, the HA Meural integration loaded both Meurals successfully!

Unfortunately, I don't know how to fix this yet or what caused the Meurals to load correctly this time around. But, I have a strange feeling these two issues are related. Due to the complexity of Sonos and the way it uses its own wireless mesh ("SonosNet") as well as the local wired and wireless LAN, I have no doubt this could create a myriad of network issues related to UPnP and create somewhat of a "UPnP Storm" so to speak. 

Hence, my question of how Meural might be related to this?

**Comment by GuySie** [comment]
@cmaglio Thanks for checking the remote URLs for me! It was a bit farfetched that it would be the same issue, as the integration is raising a different error, but I wanted to make sure. I'm also not aware of Meural using UPnP, and the integration doesn't use it either. To be honest, I'm a bit stumped here. Especially now that you did manage to get them working at the same time at least once, which throws off my thoughts that something in the code might be blocking a second device from connecting. Let me think about it some more!

**Comment by cmaglio** [comment]
No problem, both Meurals are still partially working today. They are "Available" in the interface and I can confirm that I can control them by turning them off and on via the integration. However, the "preview" image is not loading for either device, and I'm not sure if the full functionality is working or not. Let me know if there is anything that I could try to get a better handle on their state of connection.

![image](https://user-images.githubusercontent.com/37604281/203123085-bd8057ef-a980-47ba-9777-fba59c2657db.png)

I am also stumped on why my Meurals seem to behave differently than others who have successfully used the integration. Perhaps the integration just needs the ability to retry requests/commands for scenarios where there seems to be intermittent behavior?

**Comment by GuySie** [comment]
@cmaglio Oh, that's also weird that the cover images in the media player don't work. Those images don't come from your local Meural device, those come from the Meural servers - any problems with reaching your local devices should not affect getting those images, especially since the Meural servers did successfully send you the data needed for them to set up. Is the Meural integration showing any more recent errors in the logs? If so, could you send me another log snippet? Are you running pihole or any other addon that could be interfering with network traffic?

**Comment by cmaglio** [comment]
Yes, getting some different errors this time around. Here is one of them:

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/meural/media_player.py:235 
Integration: Meural (documentation, issues) 
First occurred: 10:37:22 PM (14 occurrences) 
Last logged: 10:39:31 PM

Update for media_player.north_office_wall fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/config/custom_components/meural/media_player.py", line 235, in async_update
    old_item = int(self._gallery_status["current_item"])
TypeError: list indices must be integers or slices, not str

**Comment by GuySie** [comment]
Okay, that is unexpected. Could you remove the integration and install it again, so you have to fill in your login/password again? I'm wondering if there's something wonky with your authentication on the Meural side.

I think I'm gonna send you a modified version with more debug logging, just to find out what's happening here.

**Comment by cmaglio** [comment]
Guy, I removed the integration and re-added it. The integration setup process went as smooth as it did last time. I added my credentials and then added both Meurals to an existing area. Both Meurals are available and the tiles are loading with the current image. All seems well except I am still getting some errors in the logs... so, perhaps there is still a bug hiding somewhere?

Current log error:

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/meural/pymeural.py:64
Integration: Meural (documentation, issues)
First occurred: 12:00:48 PM (2 occurrences)
Last logged: 12:00:48 PM

Update for media_player.east_office_wall fails
Update for media_player.north_office_wall fails
Traceback (most recent call last):
  File "/config/custom_components/meural/pymeural.py", line 66, in request
    resp = await self.session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_device_update
    await task
  File "/config/custom_components/meural/media_player.py", line 233, in async_update
    self._meural_device = await self.meural.get_device(self.meural_device_id)
  File "/config/custom_components/meural/pymeural.py", line 117, in get_device
    return await self.request("get", f"devices/{device_id}")
  File "/config/custom_components/meural/pymeural.py", line 64, in request
    with async_timeout.timeout(10):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 116, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by cmaglio** [comment]
I guess I'll close this based on not seeing these errors in a while. The only warning I am currently seeing in relation to the Meural integration is a warning that the scheduled update is taking longer than 10sec. Perhaps this is a time limit you want to extend in the future to prevent the warning?

![image](https://user-images.githubusercontent.com/37604281/210152735-556c0cf7-b117-4a15-95bd-4613ba765aa9.png)

Thanks for all your help with these issues!
