### ISSUE TITLE
Image preview does not match image displayed on the Canvas

### ISSUE THREAD

**Issue by Xerig** [GuySie/ha-meural#55]
This was working for me when I first started using it, but is now out of sync - and reloading or skipping to the next image does not fix the issue. All the details about the image is an image in the current playlist but just not the right one. Even the image names do not match.

**Comment by GuySie** [comment]
Hey @Xerig could you send me a debug log, from a restart to when you're skipping through the images? There was a similar issue that happened halfway through https://github.com/GuySie/ha-meural/issues/53 and I'm wondering if it's related.
