### ISSUE TITLE
 hass.helpers.aiohttp_client will be depracated in HA 2024.11 / async_forward_entry_setup  in 2025.6 and more

### ISSUE THREAD

**Issue by geeForceOne** [GuySie/ha-meural#59]
Hi @GuySie 

Not sure if you are aware of this:

Detected that custom integration 'meural' accesses hass.helpers.aiohttp_client. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from aiohttp_client directly at custom_components/meural/__init__.py, line 41: hass.helpers.aiohttp_client.async_get_clientsession()

Detected that custom integration 'meural' calls async_forward_entry_setup for integration, meural with title: 
xxx@protonmail.com and entry_id: xxx, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/meural/__init__.py, line 45: hass.async_create_task

MEDIA_CLASS_DIRECTORY was used from meural, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaClass.DIRECTORY instead, please report it to the author of the 'meural' custom integration
MEDIA_TYPE_IMAGE was used from meural, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.IMAGE instead, please report it to the author of the 'meural' custom integration
MEDIA_TYPE_PLAYLIST was used from meural, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.PLAYLIST instead, please report it to the author of the 'meural' custom integration

**Comment by kibuan** [comment]
Apparently they rescheduled the deprecation of the current implementation of the call "async_forward_entry_setup":

`Detected code that calls async_forward_entry_setup for integration meural with title: xxx@gmail.com and entry_id: xxx, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.`

Are you still maintaining this integration @GuySie?

**Comment by GuySie** [comment]
Should be fixed by https://github.com/GuySie/ha-meural/pull/58 (thanks @arcsur) - let me test a little bit and then I'll tag a new release.
